# Permalinks
permalink:           pretty

# Setup
title:               Max Garber
tagline:             Metis Data Science Blog
url:                 http://bubblebooy.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Max Garber
  url:               https://bubblebooy.github.io/max-garber-website
  #email:             zach@thisismetis.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/bubblebooy

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  #About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
